<?php
/* module for displaying stacy's quotes on the right bottom of the screen
*/
/* implementation of hook_help()
*/
function stacyImageLeftStylists_help($path, $arg){
	if($path =='admin/help#stacyImageLeftStylists'){
		$txt = 'Subu says: This module displays stacy\'s image on the left side in a block. ';
		return '<p>'.t($txt).'</p>';
	}
}

/* implementation of hook_block()
*/
function stacyImageLeftStylists_block($op='list', $delta=0, $edit=array()){
switch($op){
	case 'list':
		$blocks[0]['info'] = t('Stacy\'s left Image on the Stylist page');
		return $blocks;
	case 'view':
			$content = theme('stacyImageLeftStylists_image');
			/*$blocks['subject'] = t('Stacys image');*//* this displays the subject which i dont need now */
			$blocks['content'] = $content;
			return $blocks;

	}
}

/*function stacyquotes_theme(){
 return array(
	'stacyquotes_quote' => array(
		'arguments' => array('text' => NULL),
		),
	);
}*/
function stacyImageLeftStylists_theme(){
 return array(
	'stacyImageLeftStylists_image' => array(
		'arguments' => array(),
		),
	);
}

/* theme function for theming quotes
@param $text - stacy's image on the left side of the pages ( not the front page)
@param $origin  - source 
@return
and html themed string
*/
function theme_stacyImageLeftStylists_image(){
/* subu - the below 3 lines is to add the css file to the theme */
    $module_path = drupal_get_path('module','stacyImageLeftStylists');
    $full_path = $module_path.'/stacyImageLeftStylists.css';
    drupal_add_css($full_path);

    $output =	'<div id="stacyImageLeftStylists">'.
	       		'<a href="/" title="Home"><img width="340" height="575" alt="" src="/sites/all/themes/s4h/_img/newones/leftedge/stacy-press-left.JPG" /></a>'.
			    '</div>';
    return $output;
}