<?php
// $Id: htmlmail.tpl.php,v 1.1.2.2 2009/07/15 03:50:15 chrisherberte Exp $

/**
 * @file
 * Default template for HTML Mail
 *
 * HMTL Mail will first look in the directory of the current used
 * theme for a file named "htmlmail.tpl.php". If it exists, it will
 * be used as template for e-mails. If the file doesn't exists, 
 * this file will be used instead.
 *
 * DO NOT EDIT THIS FILE. If you want to customize the template, copy this
 * file to the directory of the used theme, and edit the copy.
 *
 * The following variables are available in this template:
 *
 *  - $body    : message body
 *  - $header  : template header
 *  - $footer  : template footer
 *  - $css     : template css
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php if ($css): ?>
<style type="text/css">
<?php print $css; ?>
</style>
<?php endif; ?>
</head>

<body id="htmlmail">

  <?php if ($header): ?>
  <div id="htmlmail-header">
  <?php print $header; ?>
  </div>
  <?php endif; ?>

<center>
	<table width="969" cellpadding="0" cellspacing="0" border="0" bgcolor="#000000">
		<tr>
			<td colspan="7" width="969" height="145">
				<a href="http://styleforhire.com/" target="_blank"><img src="http://test.styleforhire.com/sites/all/themes/s4h/email/logo.gif" alt="Style For Hire" width="969" height="145" border="0" style="display:block;" /></a>
			</td>
		</tr>
		<tr>
			<td width="120" height="52">
				<a href="##" target="_blank"><img src="http://test.styleforhire.com/sites/all/themes/s4h/email/about.gif" alt="about us" width="120" height="52" border="0" style="display:block;" /></a>
			</td>
			<td width="110" height="52">
				<a href="##" target="_blank"><img src="http://test.styleforhire.com/sites/all/themes/s4h/email/work.gif" alt="how we work" width="110" height="52" border="0" style="display:block;" /></a>
			</td>
			<td width="105" height="52">
				<a href="##" target="_blank"><img src="http://test.styleforhire.com/sites/all/themes/s4h/email/services.gif" alt="our services" width="105" height="52" border="0" style="display:block;" /></a>
			</td>
			<td width="123" height="52">
				<a href="##" target="_blank"><img src="http://test.styleforhire.com/sites/all/themes/s4h/email/style.gif" alt="the gift of style" width="123" height="52" border="0" style="display:block;" /></a>
			</td>
			<td width="186" height="52">
				<a href="##" target="_blank"><img src="http://test.styleforhire.com/sites/all/themes/s4h/email/network.gif" alt="stylists: join our network" width="186" height="52" border="0" style="display:block;" /></a>
			</td>
			<td width="147" height="52">
				<a href="##" target="_blank"><img src="http://test.styleforhire.com/sites/all/themes/s4h/email/stylist.gif" alt="find a stylist" width="147" height="52" border="0" style="display:block;" /></a>
			</td>
			<td width="178" height="52" bgcolor="#000000"><div style="width:178px;">&nbsp;</div></td>
		</tr>
	</table>
	<table width="969" cellpadding="0" cellspacing="0" border="0"  
bgcolor="#867b6c"><tr>
			<td width="33" bgcolor="#867b6c"><div  
style="width:33px;">&nbsp;</div></td>
			<td width="15" bgcolor="#ffffff" valign="bottom"><img  
src="http://test.styleforhire.com/sites/all/themes/s4h/email/corner.gif" width="15" height="62" border="0" style="display:block;" /></div></td>
			<td width="672" bgcolor="#ffffff" align="left" valign="bottom"  
style="line-height:19px;">
				<span style="font-size:15px;line-height:19px;color:#877c6d;font-family:arial,verdana,sans-serif;text-align:left;">
<?php print $body; ?>
				</span>
			<img  
src="http://test.styleforhire.com/sites/all/themes/s4h/email/quote.gif"  
alt="quote" width="672" height="62" border="0" style="display:block;" /></td>
	<td width="216" valign="bottom" align="right" bgcolor="#ffffff" style="display:inline;"><img  
src="http://test.styleforhire.com/sites/all/themes/s4h/email/stacy-face.jpg" alt="stacy" width="216" height="402" border="0"  
style="line-height:0;margin:0;padding:0;" /></td>
	<td width="33"><div style="width:33px;">&nbsp;</div></td></tr>
	<tr><td colspan="5" width="969" height="20" bgcolor="#867b6c"><div  
style="width:969px;">&nbsp;</div></td>
		</tr></table>
	<div style="line-height:20px;">&nbsp;</div>
</center>

  <?php if ($footer): ?>
  <div id="htmlmail-footer">
  <?php print $footer; ?>
  </div>
  <?php endif; ?>

</body>
</html>
