<?php
// $Id: appointment_manage.module $



// Implementation of hook_theme()
function appointment_manage_theme() {
  return array(
		'appointment_manage_main_tpl' => array(
			'template'=>'appointment_manage.main',
			'arguments' => array('data'=>NULL),
		)
		
  );
}

// implementation of hook_menu()
function appointment_manage_menu() {
  $items = array();
	

		$items['admin/content/node/appointment_manage'] = array(
		  'title' => t('Appointment manage'),
      'page callback' => 'appointment_manage_time',
	  	'access arguments' => array('administer site configuration'),
	  //	'type' => MENU_CALLBACK,			   
		);			   

	
	  $items['rating-stylist'] = array(
		  'page callback' => 'appointment_manage_rating_stylist',
		  'access arguments' => array('access content'),
		  'type' => MENU_CALLBACK,
    );

	$items['rating-stylist-success'] = array(
		'page callback' => 'appointment_manage_rating_stylist_success',
		'access arguments' => array('view eskifurimgsys'),
		'type' => MENU_CALLBACK,
    );
	
  return $items;
}

/*
// Implementation of hook_perm()
function appointment_manage_perm() {
  return array('view appointment_manage', 'insert appointment_manage', 'update appointment_manage', 'delete appointment_manage');
}
*/

function appointment_manage_rating_stylist() {
  drupal_add_js(drupal_get_path('module', 'appointment_manage') .'/js/appointment_manage.js');
  //drupal_add_css(drupal_get_path('module', 'appointment_manage') .'/css/appointment_manage.css');
	$output = '';
	//drupal_set_title(t('Thank you for your recent appointment with a Style for Hire stylist!'));	
	$heading = '<h1>'.t('Thank you for your recent appointment with a Style for Hire stylist!').'</h1>';
	$output .= $heading.'<div class="para-with-space">Your feedback helps us improve our service. Please rate your stylist in the following areas.</div>';	
	$form_close['close'] = array(
    '#type' => 'button',
    '#value' => t('Close'),
    '#attributes' => array('class' => 'rating_form_close'),
  );
  $ucode = arg(1);
  $output_close = drupal_render($form_close);
  $output .= '<div style="display:none;" class="thanksbox">Thanks for you feedback!<br><br>We look forward to working with you in the future.<br><br><div align="center">'.$output_close.'</div></div>';
  $output .= drupal_get_form('appointment_manage_rating_stylist_form', $ucode);
  
	return $output;  
}

function appointment_manage_rating_stylist_form($form_state, $ucode) {
 
	$rating_star = '<div style="width:80px; display:inline; float:left;">Timeliness&nbsp;</div>' . '<div class="rating_timelines">'. theme_fivestar_preview_widget('') . '</div>';
	$rating_star .= '<div style="width:80px; display:inline; float:left;">Courtesy&nbsp;</div>' . '<div class="rating_courtesy">'. theme_fivestar_preview_widget('') . '</div>';
	$rating_star .= '<div style="width:80px; display:inline; float:left;">Expertise&nbsp;</div>' . '<div class="rating_expertise">'. theme_fivestar_preview_widget('') . '</div>';
	$rating_star .= '<div style="width:80px; display:inline; float:left;">Attitude&nbsp;</div>' . '<div class="rating_attitude">'. theme_fivestar_preview_widget('') . '</div>';

 
  $form['rating_star'] = array('#value'=> $rating_star);
  $form['rating_comment'] = array(
    '#type' => 'textarea',
    '#title' => t('Comment'),
    '#default_value' => '',
    '#required' => FALSE,
    '#cols' => 60,
    '#rows' => 6,
	  '#resizable' => FALSE,
	  '#description' => '',
  );
  $form['rating_timelines'] = array(
  		'#type' => 'hidden',
			'#value' => 0,
	);  
  $form['rating_courtesy'] = array(
  		'#type' => 'hidden',
			'#value' => 0,
	);
  $form['rating_expertise'] = array(
  		'#type' => 'hidden',
			'#value' => 0,
	);  	
  $form['rating_attitude'] = array(
  		'#type' => 'hidden',
			'#value' => 0,
	);
  $form['rating_ucode'] = array(
  		'#type' => 'hidden',
			'#value' => $ucode,
	);
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Rating'),
  );
  $form['#ajaxsubmit'] = TRUE;
  //$form['#ajaxsubmit_callbacks'] = array('');
  $form['#submit'][] = 'appointment_manage_rating_stylist_submit';

  
  return $form;
}



function appointment_manage_rating_stylist_submit($form, &$form_state) {
 
 $ucode = $form['#post']['rating_ucode'];
 $timelines = $form['#post']['rating_timelines'];
 $courtesy = $form['#post']['rating_courtesy'];
 $expertise = $form['#post']['rating_expertise'];
 $attitude = $form['#post']['rating_attitude'];
 $status = 1;
 $credit = 5;
 $rating_date = time();
 $comment = $form['#post']['rating_comment'];
 
  db_query("UPDATE  {rating_stylist} 
    SET timelines=%d, 
        courtesy=%d,
        expertise=%d, 
        attitude=%d, 
        status=%d, 
        credit=%f, 
        comment='%s', 
        rating_date=%d 
    WHERE ucode='%s'", 
      $timelines, $courtesy, $expertise, $attitude, $status, $credit, $comment, $rating_date, $ucode);

}


function appointment_manage_rating_stylist_success() {
  $output = '<div>as;dj;ajg jag;ljadf;lgj la;jglajgj;gddsa</div>';
  echo $output;
}


function appointment_manage_time() {
  $output = '';
 
  drupal_add_css(drupal_get_path('module', 'jquery_ui') .'/jquery.ui/themes/default/ui.all.css', 'module');
  drupal_add_js(drupal_get_path('module', 'jquery_ui') .'/jquery.ui/ui/ui.datepicker.js', 'module');
  
  drupal_set_title(t('Edit appointment time'));
  date_default_timezone_set('America/New_York');
   
  if ( ((isset($_POST['startDate'])) && (!empty($_POST['startDate']))) && ((isset($_POST['endDate'])) && (!empty($_POST['endDate']))) ) {
    $_SESSION['startDate'] = $_POST['startDate'];
    $_SESSION['endDate'] = $_POST['endDate'];
  } 
    
     
  $output .= appointment_manage_formdate_show_form();   

  date_default_timezone_set('America/New_York');
  if ( ((isset($_SESSION['startDate'])) && (!empty($_SESSION['startDate']))) && ((isset($_SESSION['endDate'])) && (!empty($_SESSION['endDate']))) ) {
    $startDate = explode('/', $_SESSION['startDate']);
    $endDate = explode('/', $_SESSION['endDate']);
        
    $start_dateM = $startDate[0];
    $start_dateD = $startDate[1];
    $start_dateY = $startDate[2];    
 
    $end_dateM = $endDate[0];
    $end_dateD = $endDate[1];
    $end_dateY = $endDate[2];
   
    $sdate = mktime(0, 0, 0, $start_dateM, $start_dateD, $start_dateY); 
    $edate = mktime(0, 0, 0, $end_dateM, $end_dateD, $end_dateY);
    
    $appointment_result = db_query('SELECT * FROM {content_type_appointment} 
                                                    WHERE field_apt_date_value >= %d 
                                                      AND field_apt_date_value2 <= %d 
                                                      AND field_apt_date_value IS NOT NULL 
                                                      AND field_apt_date_value2 IS NOT NULL', $sdate, $edate);
    $items = array();
    $data = array();
    $elem = 0;
    while($item = db_fetch_object($appointment_result)) {
      $items[] = $item;
      $user_object = user_load($item->field_apt_stylist_uid);
      $date_appointment = date("m/d/Y", $item->field_apt_date_value).'/'.date("m/d/Y", $item->field_apt_date_value2);
      
      $sdate_appointment = date("m/d/Y", $item->field_apt_date_value);
      $edate_appointment = date("m/d/Y", $item->field_apt_date_value2);
      
      $data[$elem]['stylist'] = $user_object->name . '<br>' . $user_object->mail;
      if ($sdate_appointment != $edate_appointment) {
        $data[$elem]['date'] = $sdate_appointment.'<br>'.$edate_appointment;
      } else {
        $data[$elem]['date'] = $sdate_appointment;
      }
      
      $appointment_type_result = db_fetch_object(db_query('SELECT title FROM {node} WHERE nid = %d', $item->field_apt_type_nid));      
      
      $data[$elem]['stime'] = date("h:i a", $item->field_apt_date_value);
      $data[$elem]['etime'] = date("h:i a", $item->field_apt_date_value2);
      $data[$elem]['customer'] = $item->field_apt_name_value. ' ' . $item->field_apt_fname_value . '<br>' . $item->field_apt_phone_value;
      $data[$elem]['appointment_type'] = $appointment_type_result->title;

      $data[$elem]['increments'] = appointment_manage_addtime_show($item->vid, $item->field_apt_date_value2);
      
      $elem++;
    }                                                 
  }
  
      $header['stylist'] = 'Stylist';
      $header['date'] = 'Date';
      $header['stime'] = 'Sttart date';
      $header['etime'] = 'End date';
      $header['customer'] = 'Customer';
      $header['appointment_type'] = 'Appointment type';
      $header['increments'] = 'Add 30 minute increments';
  
  $output .= theme('table', $header, $data);
  $output .= theme('appointment_manage_main_tpl', $data);



	return $output;
}



function appointment_manage_formdate_show_form($appointment_id) {
  return drupal_get_form('appointment_manage_formdate_form');
}

function appointment_manage_formdate_form($form_state) {
  $form['startDate'] = array(
    '#type' => 'textfield',
    '#value' => $_SESSION['startDate'],
    '#title' => t('From'),
    '#id' => 'startDate'
  );
  $form['endDate'] = array(
    '#type' => 'textfield',
    '#value' => $_SESSION['endDate'],
    '#title' => t('To'),
    '#id' => 'endDate'
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go'),
  );
  $form['#validate'][] = 'appointment_manage_formdate_validate';
  $form['#submit'][] = 'appointment_manage_submit';
  
  return $form;
}


function appointment_manage_addtime_show($appointment_id='0', $old_time=0) {
  return drupal_get_form('appointment_manage_addtime_form', $appointment_id, $old_time);
}
function appointment_manage_addtime_form($form_state, $appointment_id='0', $old_time=0) {
  
  $options_array = array();  
  for ($i=0.5; $i<=10; $i=$i+0.5 ) {
    $options_array[$i*10] = $i.' hrs';
  }
  
  $form['time'] = array(
      '#type' => 'select',
      '#default_value' => 'teaser',
      '#options' => $options_array,
  );
  
  $form['appointment_id'] = array(
  		'#type' => 'hidden',
			'#value' => $appointment_id,
	);	

  $form['old_time'] = array(
  		'#type' => 'hidden',
			'#value' => $old_time,
	);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go'),
  );
  $form['#submit'][] = 'appointment_manage_addtime_submit';
  //$form['#validate'][] = 'appointment_manage_formdate_validate';
  //$form['#submit'][] = 'appointment_manage_submit';
  
  return $form;
}



function appointment_manage_formdate_validate($form, &$form_state) {
}


function appointment_manage_addtime_submit($form, &$form_state) {
   date_default_timezone_set('America/New_York');
 
   $time = $form['#post']['time']/10*60;
   $old_time = $form['#post']['old_time'];
   $vid =  $form['#post']['appointment_id'];
   $date_time_array = getdate($old_time);

   $hours = $date_time_array['hours'];
   $minutes = $date_time_array['minutes'];
   $seconds = $date_time_array['seconds'];
   $month = $date_time_array['mon'];
   $day = $date_time_array['mday'];
   $year = $date_time_array['year'];

   $new_time = mktime($hours,$minutes+$time,$seconds,$month,$day,$year);
 
   db_query("UPDATE {content_type_appointment} SET field_apt_date_value2='%d' WHERE vid=%d ", $new_time, $vid);

}


// Implementation of hook_form_alter()
function appointment_manage_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'user_login') {
     $form['forgot'] = array('#value'=> '<a style="float:left; width:252px; font-size:0.85em;" class="popups" href=' . url('user/password') . '>Forgot your password?</a><br>', '#weight' => 10);
     $form['create'] = array('#value'=> '<div style="padding-top:20px;"><span style="font-weight:bold;">Click here to create a new account - </span>&nbsp;<a class="popups create_account_popup" href=' . url('user/register') . '>Register now</a></div><br>', '#weight' => 20);
     
     //$form['submit'] = array('#weight' => 2);	
  }

}  
