<?php

function remove_tabs_menu_alter(&$items) {
  // Removing certain local navigation tabs that are either undesired or need to be custom relocated.
  // Set these tabs to MENU_CALLBACK, so they still register the path, but just don't show the tab:
  //$items['user/%user/edit']['type'] = MENU_CALLBACK;
  //$items['user/%user/edit/clients_file']['type'] = MENU_CALLBACK;
  //$items['user/%user/edit/preferences']['type'] = MENU_CALLBACK;
  //$items['user/%user/edit/profile']['type'] = MENU_CALLBACK;
  //$items['user/%user/edit/stylist_application']['type'] = MENU_CALLBACK;
  //$items['user/%user/edit/stylists_file']['type'] = MENU_CALLBACK;
 }
